In [ ]:
from keras.datasets import mnist

# loading the dataset
(X_train, y_train), (X_test, y_test) = mnist.load_data()
# let's print the shape of the dataset

11493376/11490434 [==============================] - 0s 0us/step


In [ ]:
print("X_train shape", X_train.shape)
print("y_train shape", y_train.shape)
print("X_test shape", X_test.shape)
print("y_test shape", y_test.shape)

X_train shape (60000, 28, 28)
y_train shape (60000,)
X_test shape (10000, 28, 28)
y_test shape (10000,)


In [ ]:
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Conv2D, MaxPool2D
from keras.utils import np_utils


# Flattening the images from the 28x28 pixels to 1D 787 pixels
X_train = X_train.reshape(60000, 784)
X_test = X_test.reshape(10000, 784)
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')

# normalizing the data to help with the training
X_train /= 255
X_test /= 255

# one-hot encoding using keras' numpy-related utilities
n_classes = 10
print("Shape before one-hot encoding: ", y_train.shape)
Y_train = np_utils.to_categorical(y_train, n_classes)
Y_test = np_utils.to_categorical(y_test, n_classes)
print("Shape after one-hot encoding: ", Y_train.shape)

# building a linear stack of layers with the sequential model
model = Sequential()
# hidden layer
model.add(Dense(100, input_shape=(784,), activation='relu'))
# output layer
model.add(Dense(10, activation='softmax'))

# looking at the model summary
model.summary()
# compiling the sequential model
model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')
# training the model for 10 epochs
model.fit(X_train, Y_train, batch_size=128, epochs=10, validation_data=(X_test, Y_test))

Shape before one-hot encoding:  (60000,)
Shape after one-hot encoding:  (60000, 10)
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 100)               78500     
_________________________________________________________________
dense_1 (Dense)              (None, 10)                1010      
Total params: 79,510
Trainable params: 79,510
Non-trainable params: 0
_________________________________________________________________
Epoch 1/10
469/469 [==============================] - 1s 3ms/step - loss: 0.3858 - accuracy: 0.8943 - val_loss: 0.2159 - val_accuracy: 0.9393
Epoch 2/10
469/469 [==============================] - 1s 3ms/step - loss: 0.1833 - accuracy: 0.9479 - val_loss: 0.1530 - val_accuracy: 0.9539
Epoch 3/10
469/469 [==============================] - 1s 3ms/step - loss: 0.1337 - accuracy: 0.9616 - val_loss: 0.1175 - val_accuracy: 0.9657
Epoc

In [ ]:
predictions = model.predict_classes(X_test)
print(predictions.shape)


(10000,)


In [ ]:
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_test, predictions)

In [ ]:
print('Confusion Matrix\n')
print(confusion)

Confusion Matrix

[[ 971    0    1    0    2    1    3    1    1    0]
 [   0 1124    4    0    0    1    3    0    3    0]
 [   5    2 1004    0    2    0    3    6    9    1]
 [   0    0    9  987    0    4    0    2    7    1]
 [   3    0    3    1  959    0    2    2    1   11]
 [   2    0    0    8    0  874    4    1    3    0]
 [   7    3    3    0    4    7  930    0    4    0]
 [   0    2    9    0    2    0    0 1007    1    7]
 [   4    0    4    4    3    3    2    4  946    4]
 [   4    3    0    5   11    3    0    5    2  976]]


In [ ]:
from sklearn.metrics import accuracy_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_test, predictions)))


Accuracy: 0.98

